# Generated by Django 5.0 on 2024-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "managed": True,
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="users",
        ),
    ]
