# Generated by Django 5.0 on 2023-12-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pacientes_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_paciente", models.CharField(max_length=255)),
                ("cpf_paciente", models.CharField(max_length=11, unique=True)),
                ("nome_medico", models.CharField(max_length=255)),
                ("data_agendamento", models.DateField()),
                ("descricao_consulta", models.TextField()),
                ("tipo_consulta", models.CharField(max_length=100)),
                ("status_agendamento", models.CharField(max_length=50)),
                ("telefone_paciente", models.CharField(max_length=20)),
                ("email_paciente", models.EmailField(max_length=254)),
                ("observacoes", models.TextField()),
                ("local_consulta", models.CharField(max_length=255)),
                (
                    "valor_consulta",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("posicao_fila", models.IntegerField()),
                ("crm_medico", models.CharField(max_length=20)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes_app.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
    ]
