# Generated by Django 5.0 on 2023-12-29 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="agendamentos",
            table="agendamentos",
        ),
    ]
