# Generated by Django 5.0 on 2023-12-31 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "managed": True,
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelTable(
            name="notification",
            table="notification",
        ),
    ]
