# Generated by Django 5.0 on 2024-01-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicos_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicos",
            name="especializacao",
            field=models.CharField(
                choices=[
                    ("cardiologia", "Cardiologia"),
                    ("ortopedia", "Ortopedia"),
                    ("Ginecologista", "Ginecologista"),
                    ("Cardiologista", "Cardiologista"),
                ],
                max_length=255,
            ),
        ),
    ]
