# Generated by Django 5.0 on 2024-01-03 20:03

import medicos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicos_app", "0002_alter_medicos_especializacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicos",
            name="cbo",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="medicos",
            name="crm",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[medicos_app.models.validate_crm_length],
            ),
        ),
        migrations.AlterField(
            model_name="medicos",
            name="especializacao",
            field=models.CharField(
                choices=[
                    (
                        "Especialização médica e mercado de trabalho",
                        "Especialização médica e mercado de trabalho",
                    ),
                    (
                        "Residência Médica e Título de Especialista",
                        "Residência Médica e Título de Especialista",
                    ),
                    ("Especialista em Acupuntura", "Especialista em Acupuntura"),
                    (
                        "Especialista em Alergia e Imunologia",
                        "Especialista em Alergia e Imunologia",
                    ),
                    (
                        "Especialista em Anestesiologia",
                        "Especialista em Anestesiologia",
                    ),
                    ("Especialista em Angiologia", "Especialista em Angiologia"),
                    ("Especialista em Cardiologia", "Especialista em Cardiologia"),
                    (
                        "Especialista em Cirurgia Cardiovascular",
                        "Especialista em Cirurgia Cardiovascular",
                    ),
                    (
                        "Especialista em Cirurgia da Mão",
                        "Especialista em Cirurgia da Mão",
                    ),
                    (
                        "Especialista em Cirurgia de Cabeça e Pescoço",
                        "Especialista em Cirurgia de Cabeça e Pescoço",
                    ),
                    (
                        "Especialista em Cirurgia do Aparelho Digestivo",
                        "Especialista em Cirurgia do Aparelho Digestivo",
                    ),
                    (
                        "Especialista em Cirurgia Geral",
                        "Especialista em Cirurgia Geral",
                    ),
                    (
                        "Especialista em Cirurgia Oncológica",
                        "Especialista em Cirurgia Oncológica",
                    ),
                    (
                        "Especialista em Cirurgia Pediátrica",
                        "Especialista em Cirurgia Pediátrica",
                    ),
                    (
                        "Especialista em Cirurgia Plástica",
                        "Especialista em Cirurgia Plástica",
                    ),
                    (
                        "Especialista em Cirurgia Torácica",
                        "Especialista em Cirurgia Torácica",
                    ),
                    (
                        "Especialista em Cirurgia Vascular",
                        "Especialista em Cirurgia Vascular",
                    ),
                    (
                        "Especialista em Clínica Médica",
                        "Especialista em Clínica Médica",
                    ),
                    (
                        "Especialista em Coloproctologia",
                        "Especialista em Coloproctologia",
                    ),
                    ("Especialista em Dermatologia", "Especialista em Dermatologia"),
                    (
                        "Especialista em Endocrinologia e Metabologia",
                        "Especialista em Endocrinologia e Metabologia",
                    ),
                    ("Especialista em Endoscopia", "Especialista em Endoscopia"),
                    (
                        "Especialista em Gastroenterologia",
                        "Especialista em Gastroenterologia",
                    ),
                    (
                        "Especialista em Genética Médica",
                        "Especialista em Genética Médica",
                    ),
                    ("Especialista em Geriatria", "Especialista em Geriatria"),
                    (
                        "Especialista em Ginecologia e Obstetrícia",
                        "Especialista em Ginecologia e Obstetrícia",
                    ),
                    (
                        "Especialista em Hematologia e Hemoterapia",
                        "Especialista em Hematologia e Hemoterapia",
                    ),
                    ("Especialista em Homeopatia", "Especialista em Homeopatia"),
                    ("Especialista em Infectologia", "Especialista em Infectologia"),
                    ("Especialista em Mastologia", "Especialista em Mastologia"),
                    (
                        "Especialista em Medicina de Emergência",
                        "Especialista em Medicina de Emergência",
                    ),
                    (
                        "Especialista em Medicina de Família e Comunidade",
                        "Especialista em Medicina de Família e Comunidade",
                    ),
                    (
                        "Especialista em Medicina do Trabalho",
                        "Especialista em Medicina do Trabalho",
                    ),
                    (
                        "Especialista em Medicina de Tráfego",
                        "Especialista em Medicina de Tráfego",
                    ),
                    (
                        "Especialista em Medicina Esportiva",
                        "Especialista em Medicina Esportiva",
                    ),
                    (
                        "Especialista em Medicina Física e Reabilitação",
                        "Especialista em Medicina Física e Reabilitação",
                    ),
                    (
                        "Especialista em Medicina Intensiva",
                        "Especialista em Medicina Intensiva",
                    ),
                    (
                        "Especialista em Medicina Legal e Perícia Médica",
                        "Especialista em Medicina Legal e Perícia Médica",
                    ),
                    (
                        "Especialista em Medicina Nuclear",
                        "Especialista em Medicina Nuclear",
                    ),
                    (
                        "Especialista em Medicina Preventiva e Social",
                        "Especialista em Medicina Preventiva e Social",
                    ),
                    ("Especialista em Nefrologia", "Especialista em Nefrologia"),
                    ("Especialista em Neurocirurgia", "Especialista em Neurocirurgia"),
                    ("Especialista em Neurologia", "Especialista em Neurologia"),
                    ("Especialista em Nutrologia", "Especialista em Nutrologia"),
                    ("Especialista em Oftalmologia", "Especialista em Oftalmologia"),
                    (
                        "Especialista em Oncologia Clínica",
                        "Especialista em Oncologia Clínica",
                    ),
                    (
                        "Especialista em Ortopedia e Traumatologia",
                        "Especialista em Ortopedia e Traumatologia",
                    ),
                    (
                        "Especialista em Otorrinolaringologia",
                        "Especialista em Otorrinolaringologia",
                    ),
                    ("Especialista em Patologia", "Especialista em Patologia"),
                    (
                        "Especialista em Patologia Clínica/Medicina Laboratorial",
                        "Especialista em Patologia Clínica/Medicina Laboratorial",
                    ),
                    ("Especialista em Pediatria", "Especialista em Pediatria"),
                    ("Especialista em Pneumologia", "Especialista em Pneumologia"),
                    ("Especialista em Psiquiatria", "Especialista em Psiquiatria"),
                    (
                        "Especialista em Radiologia e Diagnóstico por Imagem",
                        "Especialista em Radiologia e Diagnóstico por Imagem",
                    ),
                    ("Especialista em Radioterapia", "Especialista em Radioterapia"),
                    ("Especialista em Reumatologia", "Especialista em Reumatologia"),
                    ("Especialista em Urologia", "Especialista em Urologia"),
                ],
                max_length=255,
            ),
        ),
    ]
