# Generated by Django 5.0 on 2024-01-05 01:12

import medicos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicos_app", "0003_alter_medicos_cbo_alter_medicos_crm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicos",
            name="cbo",
            field=models.CharField(
                max_length=6, validators=[medicos_app.models.validate_cbo_length]
            ),
        ),
        migrations.AlterField(
            model_name="medicos",
            name="especializacao",
            field=models.CharField(max_length=255),
        ),
    ]
